accounts/urls.py
from django.urls import path

from .views import (
    ProfileView, register_user, get_accounts,LogoutView, UserLoginView, UserBankAccountView, bank_account_create, details_bank_account,
    bank_account_edit
)


app_name = 'accounts'

urlpatterns = [
    path(
        "login/", UserLoginView.as_view(),
        name="user_login"
    ),
    path(
        "logout/", LogoutView.as_view(),
        name="user_logout"
    ),
    path(
        "register/", register_user,
        name="user_registration"
    ),
    path('accounts-report/', get_accounts, name='accounts_user'),
    path('account-bank-create/', bank_account_create, name='create_abank_account'),
    path('account-details/<str:pk>', details_bank_account, name='details'),
    path('account-edit/<str:account_no>', bank_account_edit, name='account_edit'),

    path('profile', ProfileView.as_view(), name="profile"),
    path("account-view/", UserBankAccountView.as_view(), name="account_view")
]

banking_system/urls.py
from django.contrib import admin
from django.urls import path, include, re_path
from django.views.static import serve 
from . import settings

from django.conf.urls.static import static

from core.views import HomeView, DashboardView, HomeViewIndex


urlpatterns = [
    path('', HomeViewIndex.as_view(), name="index"),
    path('admin/', admin.site.urls),
    path('blogue/', include('blogue.urls')),
    path('', include('microCredit.urls')),
    path('dashboard', DashboardView.as_view(), name='dashboard'),
    path('accounts/', include('accounts.urls', namespace='accounts')),
    path(
        'transactions/',
        include('transactions.urls', namespace='transactions')
    ),
    path('summernote/', include('django_summernote.urls')),
   re_path(r'^static/(?P<path>.*)$', serve,{'document_root': settings.STATIC_ROOT}),
   re_path(r'^media/(?P<path>.*)$', serve,{'document_root': settings.MEDIA_ROOT}),
    
]
if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

blogue/urls.py
from django.urls import path
from .views import details, like_comment, tag_details, get_articles, unlike_comment

urlpatterns = [
    path("article/<slug:slug>/details", details, name="article-details"),
    path("tag/<slug:slug>/tag-details", tag_details, name="tag-details"),
    path('get-articles/<slug:slug>/', get_articles, name='get-articles'),
    path('comment/<int:comment_id>/like/', like_comment, name='like-comment'),
    path('comment/<int:comment_id>/unlike/', unlike_comment, name='unlike-comment'),
]

accounts/forms.py
from django import forms
from django.conf import settings
from django.contrib.auth.forms import UserCreationForm
from django.db import transaction
from .models import User
from .models import User, BankAccountType, UserBankAccount, UserAddress
from .constants import GENDER_CHOICE

from django.contrib.auth.forms import UserChangeForm, UserCreationForm

class CustomUserChangeForm(UserChangeForm):
    class Meta:
        model = User
        fields = ('entreprise', 'email', 'first_name', 'last_name')  # Les champs que vous voulez inclure
        exclude = ('password',)  # Les champs que vous voulez exclure

    def __init__(self, *args, **kwargs):
        super(CustomUserChangeForm, self).__init__(*args, **kwargs)
        # Personnalisation supplémentaire ici
        self.fields['email'].widget.attrs['readonly'] = True  # Rendre le champ 'username' en lecture seule
    
class UserAddressForm(forms.ModelForm):

    class Meta:
        model = UserAddress
        fields = [
            'street_address',
            'city',
        ]

    def __init__(self, *args, **kwargs):
        super().__init__(*args, **kwargs)

        for field in self.fields:
            self.fields[field].widget.attrs.update({
                'class': (
                    'block w-full mt-1 text-sm dark:border-gray-600 dark:bg-gray-700 focus:border-purple-400 focus:outline-none focus:shadow-outline-purple dark:text-gray-300 dark:focus:shadow-outline-gray form-input'
                )
            })


class UserRegistrationForm(UserCreationForm):

    class Meta:
        model = User
        fields = [
            'first_name',
            'last_name',
            'email',
            'password1',
            'password2',
        ]

    def __init__(self, *args, **kwargs):
        super().__init__(*args, **kwargs)

        for field in self.fields:
            self.fields[field].widget.attrs.update({
                'class': (
                    'appearance-none block w-full bg-gray-200 '
                    'text-gray-700 border border-gray-200 '
                    'rounded py-3 px-4 leading-tight '
                    'focus:outline-none focus:bg-white '
                    'focus:border-gray-500'
                )
            })

class UserBankAccountForm(forms.ModelForm):
    account_type = forms.ModelChoiceField(
        queryset=BankAccountType.objects.all()
    )
   
    class Meta:
        model = UserBankAccount
        labels = {
            'name': "Nom",
            'first_name': "Nom de famille", 
            'email': "Addresse email (pas obligatoire)",
            'phone': "Numèro de téléphone", 
            'gender': "Genre", 
            'birth_date': "Date de naissance (JOUR/MOI/ANNEE)", 
            'street_address':"Addresse physique",
            
            
        }
        fields = ['name', 
                  'first_name', 
                  'email',
                  'phone', 
                  'gender', 
                  'birth_date', 
                  'street_address', 
                  'account_type',
             
                ]
        
        
    def __init__(self, *args, **kwargs):
        super().__init__(*args, **kwargs)
            
        for field in self.fields:
            self.fields[field].widget.attrs.update({
                'class': (
                    'block w-full mt-1 text-sm dark:border-gray-600 dark:bg-gray-700 focus:border-purple-400 focus:outline-none focus:shadow-outline-purple dark:text-gray-300 dark:focus:shadow-outline-gray form-input'
                )
            })     

accounts/views.py
from django.contrib import messages
from django.shortcuts import render, redirect
from django.contrib.auth import get_user_model, login, logout
from django.contrib.auth.views import LoginView
from django.shortcuts import HttpResponseRedirect
from django.views.generic import CreateView
from django.contrib.auth.mixins import LoginRequiredMixin
from django.urls import reverse_lazy
from django.views.generic import TemplateView, RedirectView, View
from banking_system import settings
from accounts.models import UserBankAccount, UserAddress, BankAccountType
from transactions import utils
from .forms import UserRegistrationForm, UserAddressForm, UserBankAccountForm
from django.shortcuts import get_object_or_404
import datetime

User = get_user_model()

def register_user(request):
    form = UserRegistrationForm(request.POST or None)
    if form.is_valid():
        user = form.save()
        login(request, user)
        messages.success(
                request,
                (
                    f'Merci de pouvoir créer un compte agent ! '
                    f'Votre nom d\'utilisateur est  {user.first_name}! '
                )
            )
        
        return redirect('accounts:accounts_user')
        
    
    context = {
        'form': form
    }
    return render(request, 'accounts/user_registration.html', context)


def get_accounts(request):
    accounts = UserBankAccount.objects.filter(user=request.user)
    
    context = {
        'accounts': accounts    
    }
    return render(request, 'accounts/accounts_user.html', context)

    
def details_bank_account(request, pk):
    accounts = UserBankAccount.objects.filter(user=request.user)
    account = accounts.get(account_no=pk)
    
    context = {
        'account': account,
        'title': f'DETAILS {pk}'
    }
    return render(request, 'accounts/details.html', context)   

class UserRegistrationView(TemplateView):
    model = User
    form_class = UserRegistrationForm
    template_name = 'accounts/user_registration.html'

    def dispatch(self, request, *args, **kwargs):
        if self.request.user.is_authenticated:
            return HttpResponseRedirect(
                reverse_lazy('transactions:transaction_report')
            )
        return super().dispatch(request, *args, **kwargs)

    def post(self, request, *args, **kwargs):
        registration_form = UserRegistrationForm(self.request.POST)
        # address_form = UserAddressForm(self.request.POST)

        if registration_form.is_valid():
            #  and address_form.is_valid()
            user = registration_form.save()
            # address = address_form.save(commit=False)
            # address.user = user
            # address.save()
           

            login(self.request, user)
            messages.success(
                self.request,
                (
                    f'Thank You For Creating A Bank Account. '
                    f'Your Account Number is {user.account.account_no}. '
                )
            )
            return HttpResponseRedirect(
                reverse_lazy('transactions:deposit_money')
            )

        return self.render_to_response(
            self.get_context_data(
                registration_form=registration_form,
                # address_form=address_form
            )
        )

    def get_context_data(self, **kwargs):
        if 'registration_form' not in kwargs:
            kwargs['registration_form'] = UserRegistrationForm()
        # if 'address_form' not in kwargs:
        #     kwargs['address_form'] = UserAddressForm()

        return super().get_context_data(**kwargs)

def bank_account_create(request):
    
    form = UserBankAccountForm()
   
    
    if request.method == "POST":
        form = UserBankAccountForm(request.POST)
        if form.is_valid():
            
            account_type = str(form.cleaned_data.get('account_type'))
            
            typeid = BankAccountType.objects.get(name=account_type)
            account_num = str(settings.ACCOUNT_NUMBER_START_FROM) + str(settings.randomGen()) + "INSP"
                
            account_bank = form.save(commit=False)
            account_bank.user = request.user
            account_bank.account_type = typeid
            
            account_bank.save()
            
            messages.success(
                    request,
                    (
                        f'Thank You For Creating A Bank Account. '
                        f'Your Account Number is {account_bank}. '
                    )
                )
                
                
            return HttpResponseRedirect(
                    reverse_lazy('accounts:account_view')
                )
             
    context = {
      'form' : form,
    }
    return render(request, 'accounts/account_create.html', context)

def bank_account_edit(request, account_no):
    # Get the existing bank account based on the provided account ID
    bank_account = get_object_or_404(UserBankAccount, account_no=account_no, user=request.user)
    
    # Initialize the form with the existing bank account data
    form = UserBankAccountForm(instance=bank_account)
    
    if request.method == "POST":
        form = UserBankAccountForm(request.POST, instance=bank_account)
        if form.is_valid():
            # Save the updated bank account details
            form.save()
            
            messages.success(
                request,
                f'Your Bank Account has been successfully updated.'
            )
            
            return HttpResponseRedirect(
                reverse_lazy('accounts:account_view')
            )
    
    context = {
        'form': form,
    }
    return render(request, 'accounts/account_create.html', context)

class UserBankAccountView(LoginRequiredMixin, View):
    
    template_name = 'accounts/account_view.html'
    context = {
        "title" : "Comptes"
    }
    
    def post(self, request, *args, **kwargs):
        
        return render(request, self.template_name, self.context)
        
    def get(self, request, *args, **kwargs):
        accounts = UserBankAccount.objects.filter(user=request.user)
        items = utils.pagination(request, accounts)
        self.context['accounts'] = items
        
        
        return render(request, self.template_name, self.context)
            
class UserLoginView(LoginView):
    template_name='accounts/user_login.html'
    redirect_authenticated_user = False

class ProfileView(View):
    template_name = "accounts/profile.html"
    
    def get(self, request, *args, **kwargs):
        
        return render(request, self.template_name)
    
    
class LogoutView(RedirectView):
    pattern_name = 'index'

    def get_redirect_url(self, *args, **kwargs):
        if self.request.user.is_authenticated:
            logout(self.request)
        return super().get_redirect_url(*args, **kwargs)

templates/accounts/account_create.html
{% extends 'core/base.html' %}
{% load crispy_forms_tags %}
{% load static %} {% block head_title %}Banking System{% endblock %} 

{% block content %} 
{% if registration_form.non_field_errors %} 
{% for error in registration_form.non_field_errors %}
<div class="bg-red-100 border border-red-400 text-red-700 px-4 py-3 rounded relative mt-2" role="alert">
    <p class="font-bold">Error!</p>
    <p class="block sm:inline">{{ error }}</p>
</div>
{% endfor %} 
{% endif %} 
{% if address_form.non_field_errors %} 
{% for error in address_form.non_field_errors %}
<div class="bg-red-100 border border-red-400 text-red-700 px-4 py-3 rounded relative mt-2" role="alert">
    <p class="font-bold">Error!</p>
    <p class="block sm:inline">{{ error }}</p>
</div>
{% endfor %} 
{% endif %}
<div class="px-3 py-4 rounded-xl">
    <h1 class="mb-4 text-lg font-semibold text-gray-600 dark:text-gray-300">CREER UN COMPTE CLIENT</h1>
    <hr />
    <div class="w-3/4 flex mt-5 justify-center">
        <div class="w-full dark:text-white">
            <form method="post" class="px-4 py-3 mb-8 bg-white rounded-lg shadow-md dark:bg-gray-800">
                {% csrf_token %}
                <div class="flex-wrap -mx-3 mb-6">
                    {{form|crispy}}
                </div>
                <br>
                <div class="flex items-center justify-between">
                    <button
                        class="bg-blue-500 hover:bg-blue-700 text-white font-bold py-2 px-4 rounded focus:outline-none focus:shadow-outline"
                        type="submit">
                        Créer un compte
                    </button>
                </div>
            </form>
        </div>
    </div>
</div>
{% endblock %}

templates/accounts/account_view.html
{% extends 'core/base.html' %}
{% load humanize %}
{% block head_title %}Transaction Report{% endblock %}
{% block head_extra %}
<script type="text/javascript" src="https://cdn.jsdelivr.net/jquery/latest/jquery.min.js"></script>
<script type="text/javascript" src="https://cdn.jsdelivr.net/momentjs/latest/moment.min.js"></script>
<script type="text/javascript" src="https://cdn.jsdelivr.net/npm/daterangepicker/daterangepicker.min.js"></script>
<link rel="stylesheet" type="text/css" href="https://cdn.jsdelivr.net/npm/daterangepicker/daterangepicker.css" />
<link href="https://cdn.jsdelivr.net/npm/bootstrap@5.0.2/dist/css/bootstrap.min.css" rel="stylesheet"
    integrity="sha384-EVSTQN3/azprG1Anm3QDgpJLIm9Nao0Yz1ztcQTwFspd3yD65VohhpuuCOmLASjC" crossorigin="anonymous">
{% endblock %}

{% block content %}
<div class="my-10 py-3 px-4  rounded-xl shadow-md p-4">
    <h1 class="font-mono font-bold text-3xl text-gray-500 pb-5 pt-2 uppercase">Comptes</h1>

    <hr />


    <!-- New Table -->
    <br>
    {% if accounts %}
    {% include 'accounts/accounts.html' %}
    {% endif %}

</div>
{% endblock %} {% block footer_extra %}
<script type="text/javascript">
    var def_date = '{{request.GET.daterange}}'
    def_date = def_date == "" ? moment().format("Y-MM-DD") + " - " + moment().format("Y-MM-DD") : def_date
    var date_split = def_date.split(" - ")
    var start_date = moment(date_split[0]).format("MM/DD/Y")
    var end_date = moment(date_split[1]).format("MM/DD/Y")
    console.log(start_date, end_date)
    $(function () {
        $('input[name="daterange"]').daterangepicker({
            autoUpdateInput: false,
            startDate: start_date,
            endDate: end_date,
            locale: {
                cancelLabel: "Clear",
            },
        });

        $('input[name="daterange"]').on("apply.daterangepicker", function (ev, picker) {
            $(this).val(picker.startDate.format("YYYY-MM-DD") + " - " + picker.endDate.format("YYYY-MM-DD"));
            $('#filter').submit()
        });

        $('input[name="daterange"]').on("cancel.daterangepicker", function (ev, picker) {
            $(this).val("");
            $('#filter').submit()
        });
    });
</script>
{% endblock %}

templates/accounts/accounts.html
{% load static %}

<div class="relative w-full max-w-xl mr-6 focus-within:text-purple-500">
    <div class="absolute inset-y-0 flex items-center pl-2">
        <svg class="w-4 h-4" aria-hidden="true" fill="currentColor" viewBox="0 0 20 20">
            <path
                fill-rule="evenodd"
                d="M8 4a4 4 0 100 8 4 4 0 000-8zM2 8a6 6 0 1110.89 3.476l4.817 4.817a1 1 0 01-1.414 1.414l-4.816-4.816A6 6 0 012 8z"
                clip-rule="evenodd"></path>
        </svg>
    </div>
    <input class="w-full pl-8 pr-2 text-sm text-gray-700 placeholder-gray-600 bg-gray-100 border-0 rounded-md dark:placeholder-gray-500 dark:focus:shadow-outline-gray dark:focus:placeholder-gray-600 dark:bg-gray-700 dark:text-gray-200 focus:placeholder-gray-500 focus:bg-white focus:border-purple-300 focus:outline-none focus:shadow-outline-purple form-input"
        type="text" id="search" placeholder="Chercher un compte" aria-label="Search" />
</div>
{% if accounts %}
<div class="w-full overflow-hidden rounded-lg shadow-xs">

    <div class="w-full overflow-x-auto">
        <table class="w-full whitespace-no-wrap">
            <thead>
                <tr class="text-xs font-semibold tracking-wide text-left text-gray-500 uppercase border-b dark:border-gray-700 bg-gray-50 dark:text-gray-400 dark:bg-gray-800">
                    <th class="px-4 py-3">Client</th>
                    <th class="px-4 py-3">Montant</th>
                    <th class="px-4 py-3">Phone</th>
                    <th class="px-4 py-3">Date</th>
                    <th class="px-4 py-3">Actions</th>
                </tr>
            </thead>
            <tbody class="bg-white divide-y dark:divide-gray-700 dark:bg-gray-800" id="table">
                {% for account in accounts %}
                <tr class="text-gray-700 dark:text-gray-400">
                    <td class="px-4 py-3">
                        <div class="flex items-center text-sm">
                            <!-- Avatar with inset shadow -->
                            <div class="relative hidden w-8 h-8 mr-3 rounded-full md:block">
                                <img class="object-cover w-full h-full rounded-full" src="{% static 'img/avatar.jpg' %}" alt loading="lazy" />
                                <div class="absolute inset-0 rounded-full shadow-inner" aria-hidden="true">
                                </div>
                            </div>
                            <div>
                                <p class="font-semibold">{{account.name}} {{account.first_name}}
                                </p>
                                <p class="text-xs text-gray-600 dark:text-gray-400">
                                    {{ account.account_no }}, CDF {{account.mise}}
                                </p>
                            </div>
                        </div>
                    </td>
                    <td class="px-4 py-3 text-sm">
                        {{acciunt.account_type.name}} {{account.balance}}
                    </td>
                    <td class="px-4 py-3 text-xs">
                        <span class="px-2 py-1 font-semibold leading-tight text-green-700 bg-green-100 rounded-full dark:bg-green-700 dark:text-green-100">
                            {{account.phone}}
                        </span>
                    </td>
                    <td class="px-4 py-3 text-sm">

                        {{ account.created_at|date:"F d, Y h:i A" }}
                    </td>
                    <td class="px-4 py-3 text-sm flex justify-center">
                        <a class="btn p-2 text-white bg-purple-600" href="{% url 'accounts:account_edit' account.account_no %}">
                            Edit
                        </a>

                    </td>
                </tr>

                {% endfor %}
            </tbody>
        </table>
    </div>
    <div class="grid px-4 py-3 text-xs font-semibold tracking-wide text-gray-500 uppercase border-t dark:border-gray-700 bg-gray-50 sm:grid-cols-9 dark:text-gray-400 dark:bg-gray-800">
        {% if transactions.has_other_pages %}

        <div class="flex justify-center ">

            {% if transactions.has_previous %}

            <a href="?page={{ transactions.previous_page_number }}" class="px-3 py-1 rounded-md focus:outline-none focus:shadow-outline-purple">
            &laquo;</a> {% endif %} {% for page_number in transactions.paginator.page_range %} {% if transactions.number == page_number %}

            <button class="px-3 py-1 text-white transition-colors duration-150 bg-purple-600 border border-r-0 border-purple-600 rounded-md focus:outline-none focus:shadow-outline-purple">
                <span> 
                    {{page_number}} 
                    <span class="sr-only">

                    </span>
                </span>

            </button> {% else %}
            <a href="?page={{page_number}}" class="px-3 py-1 rounded-md focus:outline-none focus:shadow-outline-purple">
                {{ page_number }}
            </a> {% endif %} {% endfor %} {% if transactions.has_next %}

            <a href="?page={{ transactions.next_page_number }}" class="btn btn-outline-primary">&laquo;</a> {% endif %}

        </div>

        {% endif %}
    </div>
</div>
{% endif %}

<script>
    $(document).ready(function() {
        $("#search").on("input", function() {
            var filter = $(this).val().toLowerCase();
            $("#table td").each(function() {
                if ($(this).text().toLowerCase().indexOf(filter) > -1) {
                    $(this).show();
                } else {
                    $(this).hide();
                }
            });
        });
    });
</script>

templates/accounts/profile.html
{% extends 'core/base.html' %}
{% load crispy_forms_tags %}
{% load static %} {% block head_title %}Banking System{% endblock %} 

{% block content %} 

<div class="bg-white overflow-hidden shadow rounded-lg border">
    <div class="px-4 py-5 sm:px-6">
        <h3 class="text-lg leading-6 font-medium text-gray-900">
            Profile
        </h3>
        <p class="mt-1 max-w-2xl text-sm text-gray-500">
            Information vous concernant.
        </p>
    </div>
    <div class="border-t border-gray-200 px-4 py-5 sm:p-0">
        <dl class="sm:divide-y sm:divide-gray-200">
            <div class="py-3 sm:py-5 sm:grid sm:grid-cols-3 sm:gap-4 sm:px-6">
                <dt class="text-sm font-medium text-gray-500">
                   Nom complet: {{ request.user.last_name }} {{ request.first_name }}
                </dt>
                <dd class="mt-1 text-sm text-gray-900 sm:mt-0 sm:col-span-2">
                    Address email: {{ request.user.email }}
                </dd>
            </div>

            <div class="py-3 sm:py-5 sm:grid sm:grid-cols-3 sm:gap-4 sm:px-6">
                <dt class="text-sm font-medium text-gray-500">
                   Numero de téléphone
                </dt>
                <dd class="mt-1 text-sm text-gray-900 sm:mt-0 sm:col-span-2">
                    None
                </dd>
            </div>
            <div class="py-3 sm:py-5 sm:grid sm:grid-cols-3 sm:gap-4 sm:px-6">
                <dt class="text-sm font-medium text-gray-500">
                    Votre balance et gain sur retrait
                </dt>
                <dd class="mt-1 text-sm text-gray-900 sm:mt-0 sm:col-span-2">
                    CDF {{ request.user.balance }}
                </dd>
            </div>
        </dl>
    </div>
</div>
{% endblock %}

templates/accounts/user_login.html
<!DOCTYPE html>
<html :class="{ 'theme-dark': dark }" x-data="data()" lang="en">
{% load static %}

<head>
    <meta charset="UTF-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>Login - Inspiration rdc</title>
    <link href="https://fonts.googleapis.com/css2?family=Inter:wght@400;500;600;700;800&display=swap"
        rel="stylesheet" />
    <link rel="stylesheet" href="{% static 'assets/css/tailwind.output.css' %}" />
    <script src="https://cdn.jsdelivr.net/gh/alpinejs/alpine@v2.x.x/dist/alpine.min.js" defer></script>
    <script src="{% static 'assets/js/init-alpine.js' %}"></script>
</head>

<body>
    {% block content %}
    {% if form.non_field_errors %}
    {% for error in form.non_field_errors %}
    <div class="bg-red-100 border border-red-400 text-red-700 px-4 py-3 rounded relative mt-2" role="alert">
        <p class="font-bold">Error!</p>
        <p class="block sm:inline">{{ error }}</p>
    </div>
    {% endfor %} 
    {% endif %}
    <div class="flex items-center min-h-screen p-6 bg-gray-50 dark:bg-gray-900">
        <div class="grid grid-cols-1 md:grid-cols-2">
            <div class="h-32 md:h-70">
                <img aria-hidden="true" class="object-cover w-full h-full dark:hidden"
                    src="{% static 'assets/img/login-office.jpeg' %}" alt="Office" />
                <img aria-hidden="true" class="hidden object-cover w-full h-full dark:block"
                    src="{% static 'assets/img/login-office-dark.jpeg' %}" alt="Office" />
            </div>

            <div class="flex items-center justify-center p-6 sm:p-12 ">
                <div class="w-full">
                    <h1 class="mb-4 text-xl font-semibold text-gray-700 dark:text-gray-200">
                        Connexion
                    </h1>

                    <form method="post">
                        {% csrf_token %}
                        {% for hidden_field in form.hidden_fields %}
                        {{ hidden_field.errors }}
                        {{ hidden_field }}
                        {% endfor %}
                        {% for field in form.visible_fields %}

                        <label class="block dark:text-white text-sm" for="{{ field.id_for_label }}">
                            {{ field.label }}
                            <input
                                class="block w-full mt-1 text-sm dark:border-gray-600 dark:bg-gray-700 focus:border-purple-400 focus:outline-none focus:shadow-outline-purple dark:text-slate-300 dark:focus:shadow-outline-gray form-input"
                                name="{{ field.name }}" id="{{ field.id_for_label }}" type="{{ field.widget_type }}">
                        </label>


                        {% if field.errors %} {% for error in field.errors %}
                        <p class="text-red-600 text-sm italic pb-2">{{ error }}</p>
                        {% endfor %} {% endif %} {% endfor %}
                        <p class="text-white text-sm  italic pb-2">
                            Note: Si vous avez oublié votre mot de passe ou votre E-mail
                            <br> Veuillez contater l'admnistrateur. Merci !
                        </p>
                        <button
                            class="block w-full px-4 py-2 mt-4 text-sm font-medium leading-5 text-center text-white transition-colors duration-150 bg-purple-600 border border-transparent rounded-lg active:bg-purple-600 hover:bg-purple-700 focus:outline-none focus:shadow-outline-purple"
                            type="submit">
                            Sign In
                        </button>
                    </form>

                </div>




            </div>
        </div>
    </div>
    {% endblock %}

</body>

</html>

templates/accounts/user_registration.html
{% extends 'core/base.html' %} 
{% load crispy_forms_tags %}
{% load static %} {% block head_title %}{{title}}{% endblock %} {% block content %} {% if form.non_field_errors %} {% for error in form.non_field_errors %}
<div class="bg-red-100 border border-red-400 text-red-700 px-4 py-3 rounded relative mt-2" role="alert">
    <p class="font-bold">Error!</p>
    <p class="block sm:inline">{{ error }}</p>
</div>
{% endfor %} {% endif %} {% if form.non_field_errors %} {% for error in form.non_field_errors %}
<div class="bg-red-100 border border-red-400 text-red-700 px-4 py-3 rounded relative mt-2" role="alert">
    <p class="font-bold">Error!</p>
    <p class="block sm:inline">{{ error }}</p>
</div>
{% endfor %} {% endif %}
<div class="bg-white px-3 py-4 rounded-xl">
    <h1 class="font-mono font-bold text-3xl text-center pb-5">CREER UN COMPTE AGENT</h1>
    <hr />
    <div class="w-full flex mt-5 justify-center">

   
    <div class="bg-white w-8/12">
        <form method="post" class="bg-white shadow-md rounded px-8 pt-6 pb-8 mb-4">
            {% csrf_token %}
            <div class="flex-wrap -mx-3 mb-6">
                {{form|crispy}}
            </div>

            <div class="flex items-center justify-between">
                <p class="ftext-warning-600 text-sm italic pb-2">Note: Retenz bien votre mot de passe et votre E-mail pour le prochain login</p>
            </div>
            <br>
            <div class="flex items-center justify-between">
                <button class="bg-blue-500 hover:bg-blue-700 text-white font-bold py-2 px-4 rounded focus:outline-none focus:shadow-outline" type="submit">
                    Créer un compte
                </button>
            </div>
        </form>
    </div>
</div>
</div>
{% endblock %}