accounts/urls.py
from django.urls import path

from .views import (
    ProfileView, register_user, get_accounts,LogoutView, UserLoginView, UserBankAccountView, bank_account_create, details_bank_account,
    bank_account_edit
)


app_name = 'accounts'

urlpatterns = [
    path(
        "login/", UserLoginView.as_view(),
        name="user_login"
    ),
    path(
        "logout/", LogoutView.as_view(),
        name="user_logout"
    ),
    path(
        "register/", register_user,
        name="user_registration"
    ),
    path('accounts-report/', get_accounts, name='accounts_user'),
    path('account-bank-create/', bank_account_create, name='create_abank_account'),
    path('account-details/<str:pk>', details_bank_account, name='details'),
    path('account-edit/<str:account_no>', bank_account_edit, name='account_edit'),

    path('profile', ProfileView.as_view(), name="profile"),
    path("account-view/", UserBankAccountView.as_view(), name="account_view")
]

banking_system/urls.py
from django.contrib import admin
from django.urls import path, include, re_path
from django.views.static import serve 
from . import settings

from django.conf.urls.static import static

from core.views import HomeView, DashboardView, HomeViewIndex


urlpatterns = [
    path('', HomeViewIndex.as_view(), name="index"),
    path('admin/', admin.site.urls),
    path('blogue/', include('blogue.urls')),
    path('', include('microCredit.urls')),
    path('dashboard', DashboardView.as_view(), name='dashboard'),
    path('accounts/', include('accounts.urls', namespace='accounts')),
    path(
        'transactions/',
        include('transactions.urls', namespace='transactions')
    ),
    path('summernote/', include('django_summernote.urls')),
   re_path(r'^static/(?P<path>.*)$', serve,{'document_root': settings.STATIC_ROOT}),
   re_path(r'^media/(?P<path>.*)$', serve,{'document_root': settings.MEDIA_ROOT}),
    
]
if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

blogue/urls.py
from django.urls import path
from .views import details, like_comment, tag_details, get_articles, unlike_comment

urlpatterns = [
    path("article/<slug:slug>/details", details, name="article-details"),
    path("tag/<slug:slug>/tag-details", tag_details, name="tag-details"),
    path('get-articles/<slug:slug>/', get_articles, name='get-articles'),
    path('comment/<int:comment_id>/like/', like_comment, name='like-comment'),
    path('comment/<int:comment_id>/unlike/', unlike_comment, name='unlike-comment'),
]

transactions/urls.py
from django.urls import path

from .views import DepositMoneyView, WithdrawMoneyView, TransactionRepostView, TransactionCaisseView


app_name = 'transactions'


urlpatterns = [
    path("deposit/", DepositMoneyView.as_view(), name="deposit_money"),
    path("report/", TransactionRepostView.as_view(), name="transaction_report"),
    path("withdraw/", WithdrawMoneyView.as_view(), name="withdraw_money"),
    path("paiements/", TransactionCaisseView.as_view(), name="paiements")
]

core/models.py
from django.db import models

# Create your models here.

core/views.py
from django.shortcuts import render
from django.views.generic import View
from django.contrib.auth.mixins import LoginRequiredMixin
from accounts.models import UserBankAccount, User
from blogue.models import Article, Tag
from transactions import utils, models, constants

class HomeViewIndex(View):
    template_name = 'core/home.html'
    articles = Article.objects.all()[:10]
    tags = Tag.objects.all()
    
    context = {
        'title': "Home vie",
        'articles': articles,
        'tags': tags
    }
    
    def get(self, request,*args, **kwargs):
        
        return render(request, self.template_name, self.context)

class HomeView(View):
    template_name = 'index.html'
    
    context = {
        'title': "Tableau de bord"
    }
    
    def get(self, request,*args, **kwargs):
        
        print(self.context)

        return render(request, self.template_name, self.context)
    
    
class DashboardView(LoginRequiredMixin, View):
    template_name = 'core/dashboard.html'
    
    context = {
        'title': "Tableau de bord"
    }
    
    def get(self, request,*args, **kwargs):
        accounts = UserBankAccount.objects.filter(user=request.user)
        items = utils.pagination(request, accounts)
        totalclients = UserBankAccount.objects.all()
        transactions = models.Transaction.objects.all()
        
        self.context['accounts'] = items
        self.context['totalclients'] = totalclients.count
        self.context['transactions_solde_deposit'] = sum(item.amount for item in transactions.filter(transaction_type=constants.DEPOSIT))
        self.context['transactions_solde_retrailt'] = sum(item.amount for item in transactions.filter(transaction_type=constants.WITHDRAWAL))
        self.context['solde'] = sum(item.balance for item in totalclients)
        self.context['totalmembres'] = User.objects.all().count
        
        return render(request, self.template_name, self.context)    

templates/core/base.html
<!DOCTYPE html>
{% load static %}
<html :class="{ 'theme-dark': dark }" x-data="data()" lang="en">

<head>
    <meta charset="UTF-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>INSPIRATION RDC {% if title %} | {{ title }} {% endif %}</title>
    <link href="https://fonts.googleapis.com/css2?family=Inter:wght@400;500;600;700;800&display=swap"
        rel="stylesheet" />
    <link rel="stylesheet" href="{% static 'assets/css/tailwind.output.css' %}" />

    <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/flatpickr/dist/flatpickr.min.css" />

    <script src="https://cdn.jsdelivr.net/gh/alpinejs/alpine@v2.x.x/dist/alpine.min.js" defer></script>
    <script src="{% static 'assets/js/init-alpine.js' %}"></script>
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/Chart.js/2.9.3/Chart.min.css" />
    <script src="https://cdnjs.cloudflare.com/ajax/libs/Chart.js/2.9.3/Chart.min.js" defer></script>
    <script src="{% static 'assets/js/charts-lines.js' %}" defer></script>
    <script src="{% static 'assets/js/charts-pie.js' %}" defer></script>
</head>

<body>
    <div class="flex h-screen bg-gray-50 dark:bg-gray-900" :class="{ 'overflow-hidden': isSideMenuOpen }">
        {% include 'widgets/sidebar.html' %}
        <div class="flex flex-col flex-1 w-full">
            {% include 'widgets/navbar.html' %}
            <main class="h-full overflow-y-auto">
                
                {% include "partials/_messages.html" %}
                
                {% block content %}

                {% endblock %}
            </main>

        </div>

    </div>

    <script src="https://cdnjs.cloudflare.com/ajax/libs/flowbite/2.3.0/datepicker.min.js"></script>

<script src="https://cdn.jsdelivr.net/npm/flatpickr"></script>
    <script type="application/ld+json">
        {
        "@context": "https://INSPIRATIONrdc.com",
        "@type": "Person",
        "name": "IRAGI MAHESHE RODRIGUE",
        "url": "https://yourwebsite.com",
        "image": "https://yourwebsite.com/"
        }
</script>
</body>

</html>

templates/core/base_1.html
<!DOCTYPE html> {% load static %}
<html :class="{ 'theme-dark': dark }" x-data="data()" lang="en">

<head>
    <meta charset="UTF-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <meta name="author" content="Ir, IRAGI MAHESHE RODRIGUE">
    <meta name="author_gmail" content="rodrigueiragi1@gmail.com">
    <meta name="owner" content="PAULIN MAHESHE">
    <title>Inspiration RDC - Blogue {{ article.title }} {{ tag_n.name }}</title>
    <link rel="preconnect" href="https://fonts.gstatic.com/" crossorigin />
    <link rel="stylesheet" as="style" onload="this.rel='stylesheet'" href="https://fonts.googleapis.com/css2?display=swap&amp;family=Noto+Sans%3Awght%40400%3B500%3B700%3B900&amp;family=Space+Grotesk%3Awght%40400%3B500%3B700" />
    <link rel="icon" type="image/x-icon" href="data:image/x-icon;base64," />
    <script async src="https://pagead2.googlesyndication.com/pagead/js/adsbygoogle.js?client=ca-pub-7333880846224437"
     crossorigin="anonymous"></script>

    <script src="https://cdn.tailwindcss.com?plugins=forms,container-queries"></script>
    <style>
        /* Ensure the mobile menu is hidden by default */
        
        .mobile-menu {
            display: none;
        }
        /* Display the mobile menu when the menu is toggled */
        
        .mobile-menu.active {
            display: block;
        }
    </style>

</head>

<body>
    <div class="relative flex size-full min-h-screen flex-col bg-[#F8F9FB] group/design-root overflow-x-hidden" style='font-family: "Space Grotesk", "Noto Sans", sans-serif;'>
        <div class="layout-container flex h-full grow flex-col">
            {% include 'widgets/header.html' %} {% block content %} {% endblock %} {% include 'widgets/footer.html' %}
        </div>
    </div>

    <script>
        function toggleMobileMenu() {
            const menu = document.getElementById("mobileMenu");
            menu.classList.toggle("hidden");
            menu.classList.toggle("flex");
        }
    </script>
</body>

</html>

templates/core/dashboard.html
{% extends 'core/base.html' %} 
{% load static %} 

{% block content %}

<div class="container px-6 mx-auto grid">
    <h2 class="my-6 text-2xl font-semibold text-gray-700 dark:text-gray-200">
        Dashboard
    </h2>
    <!-- CTA -->

    <!-- Cards -->
    {% if request.user.is_superuser %}
    <div class="grid gap-6 mb-8 md:grid-cols-2 xl:grid-cols-4">
        <!-- Card -->
        <div class="flex items-center p-4 bg-white rounded-lg shadow-xs dark:bg-gray-800">
            <div class="p-3 mr-4 text-orange-500 bg-orange-100 rounded-full dark:text-orange-100 dark:bg-orange-500">
                <svg class="w-5 h-5" fill="currentColor" viewBox="0 0 20 20">
                    <path
                        d="M13 6a3 3 0 11-6 0 3 3 0 016 0zM18 8a2 2 0 11-4 0 2 2 0 014 0zM14 15a4 4 0 00-8 0v3h8v-3zM6 8a2 2 0 11-4 0 2 2 0 014 0zM16 18v-3a5.972 5.972 0 00-.75-2.906A3.005 3.005 0 0119 15v3h-3zM4.75 12.094A5.973 5.973 0 004 15v3H1v-3a3 3 0 013.75-2.906z">
                    </path>
                </svg>
            </div>
            <div>
                <p class="mb-2 text-sm font-medium text-gray-600 dark:text-gray-400">
                    Total clients
                </p>
                <p class="text-lg font-semibold text-gray-700 dark:text-gray-200">
                    {{totalclients}}
                </p>
            </div>
        </div>
        <!-- Card -->
        <div class="flex items-center p-4 bg-white rounded-lg shadow-xs dark:bg-gray-800">
            <div class="p-3 mr-4 text-green-500 bg-green-100 rounded-full dark:text-green-100 dark:bg-green-500">
                <svg class="w-5 h-5" fill="currentColor" viewBox="0 0 20 20">
                    <path fill-rule="evenodd"
                        d="M4 4a2 2 0 00-2 2v4a2 2 0 002 2V6h10a2 2 0 00-2-2H4zm2 6a2 2 0 012-2h8a2 2 0 012 2v4a2 2 0 01-2 2H8a2 2 0 01-2-2v-4zm6 4a2 2 0 100-4 2 2 0 000 4z"
                        clip-rule="evenodd"></path>
                </svg>
            </div>
            <div>
                <p class="mb-2 text-sm font-medium text-gray-600 dark:text-gray-400">
                    Solde de tout les comptes
                </p>
                <p class="text-lg font-semibold text-gray-700 dark:text-gray-200">
                    CDF {{ solde }}
                </p>
            </div>
        </div>
        <!-- Card -->
        <div class="flex items-center p-4 bg-white rounded-lg shadow-xs dark:bg-gray-800">
            <div class="p-3 mr-4 text-blue-500 bg-blue-100 rounded-full dark:text-blue-100 dark:bg-blue-500">
                <svg class="w-5 h-5" fill="currentColor" viewBox="0 0 20 20">
                    <path
                        d="M3 1a1 1 0 000 2h1.22l.305 1.222a.997.997 0 00.01.042l1.358 5.43-.893.892C3.74 11.846 4.632 14 6.414 14H15a1 1 0 000-2H6.414l1-1H14a1 1 0 00.894-.553l3-6A1 1 0 0017 3H6.28l-.31-1.243A1 1 0 005 1H3zM16 16.5a1.5 1.5 0 11-3 0 1.5 1.5 0 013 0zM6.5 18a1.5 1.5 0 100-3 1.5 1.5 0 000 3z">
                    </path>
                </svg>
            </div>
            <div>
                <p class="mb-2 text-sm font-medium text-gray-600 dark:text-gray-400">
                    Transaction (Depot)
                </p>
                <p class="text-lg font-semibold text-gray-700 dark:text-gray-200">
                    CDF {{transactions_solde_deposit}}
                </p>
            </div>
        </div>
        <!-- Card -->
        <div class="flex items-center p-4 bg-white rounded-lg shadow-xs dark:bg-gray-800">
            <div class="p-3 mr-4 text-teal-500 bg-teal-100 rounded-full dark:text-teal-100 dark:bg-teal-500">
                <svg class="w-5 h-5" fill="currentColor" viewBox="0 0 20 20">
                    <path fill-rule="evenodd"
                        d="M4 4a2 2 0 00-2 2v4a2 2 0 002 2V6h10a2 2 0 00-2-2H4zm2 6a2 2 0 012-2h8a2 2 0 012 2v4a2 2 0 01-2 2H8a2 2 0 01-2-2v-4zm6 4a2 2 0 100-4 2 2 0 000 4z"
                        clip-rule="evenodd"></path>
                </svg>
            </div>
            <div>
                <p class="mb-2 text-sm font-medium text-gray-600 dark:text-gray-400">
                    Transaction (Retrait)
                </p>
                <p class="text-lg font-semibold text-gray-700 dark:text-gray-200">
                    CDF {{transactions_solde_retrailt}}
                </p>
            </div>
        </div>

        <div class="flex items-center p-4 bg-white rounded-lg shadow-xs dark:bg-gray-800">
            <div class="p-3 mr-4 text-teal-500 bg-teal-100 rounded-full dark:text-teal-100 dark:bg-teal-500">
                <svg class="w-5 h-5" fill="currentColor" viewBox="0 0 20 20">
                    <path fill-rule="evenodd"
                        d="M4 4a2 2 0 00-2 2v4a2 2 0 002 2V6h10a2 2 0 00-2-2H4zm2 6a2 2 0 012-2h8a2 2 0 012 2v4a2 2 0 01-2 2H8a2 2 0 01-2-2v-4zm6 4a2 2 0 100-4 2 2 0 000 4z"
                        clip-rule="evenodd"></path>
                </svg>
            </div>
            <div>
                <p class="mb-2 text-sm font-medium text-gray-600 dark:text-gray-400">
                    Gain potentiel de retrait
                </p>
                <p class="text-lg font-semibold text-gray-700 dark:text-gray-200">
                    CDF {{ request.user.entreprise.balance }}
                </p>
            </div>
        </div>

        <div class="flex items-center p-4 bg-white rounded-lg shadow-xs dark:bg-gray-800">
            <div class="p-3 mr-4 text-teal-500 bg-teal-100 rounded-full dark:text-teal-100 dark:bg-teal-500">
                <svg class="w-5 h-5" fill="currentColor" viewBox="0 0 20 20">
                    <path fill-rule="evenodd"
                        d="M4 4a2 2 0 00-2 2v4a2 2 0 002 2V6h10a2 2 0 00-2-2H4zm2 6a2 2 0 012-2h8a2 2 0 012 2v4a2 2 0 01-2 2H8a2 2 0 01-2-2v-4zm6 4a2 2 0 100-4 2 2 0 000 4z"
                        clip-rule="evenodd"></path>
                </svg>
            </div>
            <div>
                <p class="mb-2 text-sm font-medium text-gray-600 dark:text-gray-400">
                    Gain potentiel sur credit
                </p>
                <p class="text-lg font-semibold text-gray-700 dark:text-gray-200">
                    CDF {{ request.user.entreprise.gain_surcerdit }}
                </p>
            </div>
        </div>

        <div class="flex items-center p-4 bg-white rounded-lg shadow-xs dark:bg-gray-800">
            <div class="p-3 mr-4 text-orange-500 bg-orange-100 rounded-full dark:text-orange-100 dark:bg-orange-500">
                <svg class="w-5 h-5" fill="currentColor" viewBox="0 0 20 20">
                    <path
                        d="M13 6a3 3 0 11-6 0 3 3 0 016 0zM18 8a2 2 0 11-4 0 2 2 0 014 0zM14 15a4 4 0 00-8 0v3h8v-3zM6 8a2 2 0 11-4 0 2 2 0 014 0zM16 18v-3a5.972 5.972 0 00-.75-2.906A3.005 3.005 0 0119 15v3h-3zM4.75 12.094A5.973 5.973 0 004 15v3H1v-3a3 3 0 013.75-2.906z">
                    </path>
                </svg>
            </div>
            <div>
                <p class="mb-2 text-sm font-medium text-gray-600 dark:text-gray-400">
                    Total membres
                </p>
                <p class="text-lg font-semibold text-gray-700 dark:text-gray-200">
                    {{totalmembres}}
                </p>
            </div>
        </div>
    </div>
    {% endif %}

    <!-- New Table -->
    {% if accounts %}
    {% include 'accounts/accounts.html' %}
    {% endif %}

    <!-- Charts -->
    {% if request.user.is_superuser %}
    <h2 class="my-6 text-2xl font-semibold text-gray-700 dark:text-gray-200">
        Observations Graphiques Des Activitées
    </h2>
    <div class="grid gap-6 mb-8 md:grid-cols-2">
        <div class="min-w-0 p-4 bg-white rounded-lg shadow-xs dark:bg-gray-800">
            <h4 class="mb-4 font-semibold text-gray-800 dark:text-gray-300">
                Observations
            </h4>
            <canvas id="pie"></canvas>
            <div class="flex justify-center mt-4 space-x-3 text-sm text-gray-600 dark:text-gray-400">
                <!-- Chart legend -->
                <div class="flex items-center">
                    <span class="inline-block w-3 h-3 mr-1 bg-blue-500 rounded-full"></span>
                    <span>Comptes</span>
                </div>
                <div class="flex items-center">
                    <span class="inline-block w-3 h-3 mr-1 bg-teal-600 rounded-full"></span>
                    <span>Membres</span>
                </div>
                <div class="flex items-center">
                    <span class="inline-block w-3 h-3 mr-1 bg-purple-600 rounded-full"></span>
                    <span>Gains</span>
                </div>
            </div>
        </div>
        <div class="min-w-0 p-4 bg-white rounded-lg shadow-xs dark:bg-gray-800">
            <h4 class="mb-4 font-semibold text-gray-800 dark:text-gray-300">
                Operations
            </h4>
            <canvas id="line"></canvas>
            <div class="flex justify-center mt-4 space-x-3 text-sm text-gray-600 dark:text-gray-400">
                <!-- Chart legend -->
                <div class="flex items-center">
                    <span class="inline-block w-3 h-3 mr-1 bg-teal-600 rounded-full"></span>
                    <span>Depot</span>
                </div>
                <div class="flex items-center">
                    <span class="inline-block w-3 h-3 mr-1 bg-purple-600 rounded-full"></span>
                    <span>Retrait</span>
                </div>
            </div>
        </div>
    </div>

    {% endif %}
</div>


{% endblock %}

templates/core/footer.html
<footer class="footer bg-blue-900 text-white relative pt-1 border-b-2 mt-10">
    <div class="container mx-auto px-6">
        <div class="mt-5 flex flex-col items-center">
            <div class="sm:w-2/3 text-center py-0 pb-2">
                <p class="text-md text-white font-bold mb-2">
                    © {% now "Y" %} Developed by <a href="mailto:rodrigueiragi1@gmail.com">Rodrigue</a>
                </p>
            </div>
        </div>
    </div>
</footer>

templates/core/messages.html
{% for message in messages %}
<div class="bg-teal-100 border-t-4 border-teal-500 rounded-b text-teal-900 px-4 py-3 shadow-md mt-2" role="alert">
    <div class="flex">
        <div class="py-1"><svg class="fill-current h-6 w-6 text-teal-500 mr-4" xmlns="http://www.w3.org/2000/svg" viewBox="0 0 20 20"><path d="M2.93 17.07A10 10 0 1 1 17.07 2.93 10 10 0 0 1 2.93 17.07zm12.73-1.41A8 8 0 1 0 4.34 4.34a8 8 0 0 0 11.32 11.32zM9 11V9h2v6H9v-4zm0-6h2v2H9V5z"/></svg></div>
        <div>
            <p class="font-bold">Success!</p>
            <p class="text-sm">{{ message }}</p>
        </div>
    </div>
</div>
{% endfor %}

templates/core/navbar.html
<nav class="flex items-center justify-between flex-wrap bg-blue-400 p-6 px-10">
    <div class="flex items-center flex-shrink-0 text-white mr-6">
        <span class="font-semibold text-xl tracking-tight text-white">Akili ni mali System</span>
    </div>
    <div class="block lg:hidden">
        <button class="flex items-center px-3 py-2 border rounded text-white border-white-400 hover:text-white hover:border-white">
            <svg class="fill-current h-3 w-3" viewBox="0 0 20 20" xmlns="http://www.w3.org/2000/svg"><title>Menu</title><path d="M0 3h20v2H0V3zm0 6h20v2H0V9zm0 6h20v2H0v-2z"/></svg>
        </button>
    </div>
    <div class="w-full block flex-grow lg:flex lg:items-center lg:w-auto px-10">
        {% if request.user.is_authenticated %}
            <div class="text-md lg:flex-grow">
                <a href="{% url 'transactions:transaction_report' %}" class="block mt-4 lg:inline-block lg:mt-0 text-white hover:text-white mr-4">
                    Home
                </a>
                <a href="{% url 'transactions:deposit_money' %}" class="block mt-4 lg:inline-block lg:mt-0 text-white hover:text-white mr-4">
                    Dépôt
                </a>
                <a href="{% url 'transactions:withdraw_money' %}" class="block mt-4 lg:inline-block lg:mt-0 text-white hover:text-white">
                    Rétrait
                </a>
                <a href="{% url 'accounts:create_abank_account' %}" class="block mt-4 lg:inline-block lg:mt-0 text-white hover:text-white">Créer un compte réel</a>
                <a href="{% url 'accounts:subaccount' %}" class="block mt-4 lg:inline-block lg:mt-0 text-white hover:text-white">
                    Sous comptes
                </a>
            </div>
            <div class="flex w-auto">
                <div class="text-blue-900 my-auto font-black px-5">Bienvenue, {{ request.user.first_name }} {{ request.user.last_name }}!</div>
                <a href="{% url 'accounts:user_logout' %}" class="mx-2 inline-block font-medium text-sm px-4 py-2 leading-none bg-blue-900 rounded text-white border-white hover:border-transparent hover:text-gray-800 hover:bg-white mt-4 lg:mt-0">Logout</a>
            </div>
        {% else %}
            <div class="text-md lg:flex-grow"></div>
            <div>
                <a href="{% url 'accounts:user_login' %}" class="mr-2 inline-block font-medium text-sm px-4 py-2 leading-none bg-blue-900 rounded text-white border-white hover:border-transparent hover:text-gray-800 hover:bg-white mt-4 lg:mt-0">Login</a>
            </div>
            <div>
                <a href="{% url 'accounts:user_registration' %}" class="inline-block font-medium text-sm px-4 py-2 leading-none bg-blue-900 rounded text-white border-white hover:border-transparent hover:text-gray-800 hover:bg-white mt-4 lg:mt-0">Register</a>
            </div>
        {% endif %}
    </div>
</nav>

templates/core/tag-details.html
{% extends 'core/base_1.html' %} {% block content %}
<div class="flex flex-col md:flex-row gap-4 px-6 py-5">
    <!-- Sidebar for tags -->
    <div class="w-full md:w-80 bg-[#F8F9FB] p-4 rounded-lg shadow-md">
        <h1 class="text-[#141C24] text-lg font-medium mb-4">Mot cles</h1>
        <div class="flex flex-col gap-2">
            {% for tag in tags %} {% if tag_n.slug == tag.slug %} {% else %}
            <a href="{% url 'tag-details' tag.slug %}" class="tag px-3 py-2 rounded-xl bg-[#E4E9F1] text-[#141C24] text-sm font-medium leading-normal cursor-pointer hover:bg-[#d3d8e0]">
                {{ tag.name }}
            </a>{% endif %} {% endfor %}
        </div>
    </div>

    <!-- Articles section -->
    <div class="flex-1 max-w-full">
        <p id="tag-name" class="text-[#3F5374] text-sm font-normal pb-3 pt-1 px-4">Articles |  {{ tag_n.name }}</p>

        <div id="articles" class="grid grid-cols-1 sm:grid-cols-2 lg:grid-cols-3 gap-6 px-4">
            {% if articles %} {% for article in articles %}
            <a href="{% url 'article-details' article.slug %}" class="flex flex-col gap-4 rounded-lg overflow-hidden shadow-lg hover:shadow-xl transition-shadow duration-300 ease-in-out">
                <img src="{{ article.imageUrl }}" alt="{{ article.title }}" class="w-full bg-center bg-no-repeat aspect-video bg-cover" style='background-image: url("");'>
                <div class="p-4">
                    <p class="text-[#141C24] text-lg font-semibold leading-snug">
                        {{ article.title }}
                    </p>
                    <p class="text-[#3F5374] text-sm leading-relaxed mt-2">
                        {{ article.get_plain_text_content|truncatewords:10 }}
                    </p>
                </div>
            </a>
            {% endfor %} {% else %}
            <p class="text-[#3F5374] text-sm font-normal">Aucun article trouvé pour ce tag.</p>
            {% endif %}
        </div>
    </div>
</div>
{% endblock %}