accounts/urls.py
from django.urls import path

from .views import (
    ProfileView, register_user, get_accounts,LogoutView, UserLoginView, UserBankAccountView, bank_account_create, details_bank_account,
    bank_account_edit
)


app_name = 'accounts'

urlpatterns = [
    path(
        "login/", UserLoginView.as_view(),
        name="user_login"
    ),
    path(
        "logout/", LogoutView.as_view(),
        name="user_logout"
    ),
    path(
        "register/", register_user,
        name="user_registration"
    ),
    path('accounts-report/', get_accounts, name='accounts_user'),
    path('account-bank-create/', bank_account_create, name='create_abank_account'),
    path('account-details/<str:pk>', details_bank_account, name='details'),
    path('account-edit/<str:account_no>', bank_account_edit, name='account_edit'),

    path('profile', ProfileView.as_view(), name="profile"),
    path("account-view/", UserBankAccountView.as_view(), name="account_view")
]

banking_system/urls.py
from django.contrib import admin
from django.urls import path, include, re_path
from django.views.static import serve 
from . import settings

from django.conf.urls.static import static

from core.views import HomeView, DashboardView, HomeViewIndex


urlpatterns = [
    path('', HomeViewIndex.as_view(), name="index"),
    path('admin/', admin.site.urls),
    path('blogue/', include('blogue.urls')),
    path('', include('microCredit.urls')),
    path('dashboard', DashboardView.as_view(), name='dashboard'),
    path('accounts/', include('accounts.urls', namespace='accounts')),
    path(
        'transactions/',
        include('transactions.urls', namespace='transactions')
    ),
    path('summernote/', include('django_summernote.urls')),
   re_path(r'^static/(?P<path>.*)$', serve,{'document_root': settings.STATIC_ROOT}),
   re_path(r'^media/(?P<path>.*)$', serve,{'document_root': settings.MEDIA_ROOT}),
    
]
if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

blogue/urls.py
from django.urls import path
from .views import details, like_comment, tag_details, get_articles, unlike_comment

urlpatterns = [
    path("article/<slug:slug>/details", details, name="article-details"),
    path("tag/<slug:slug>/tag-details", tag_details, name="tag-details"),
    path('get-articles/<slug:slug>/', get_articles, name='get-articles'),
    path('comment/<int:comment_id>/like/', like_comment, name='like-comment'),
    path('comment/<int:comment_id>/unlike/', unlike_comment, name='unlike-comment'),
]

accounts/forms.py
from django import forms
from django.conf import settings
from django.contrib.auth.forms import UserCreationForm
from django.db import transaction
from .models import User
from .models import User, BankAccountType, UserBankAccount, UserAddress
from .constants import GENDER_CHOICE

from django.contrib.auth.forms import UserChangeForm, UserCreationForm

class CustomUserChangeForm(UserChangeForm):
    class Meta:
        model = User
        fields = ('entreprise', 'email', 'first_name', 'last_name')  # Les champs que vous voulez inclure
        exclude = ('password',)  # Les champs que vous voulez exclure

    def __init__(self, *args, **kwargs):
        super(CustomUserChangeForm, self).__init__(*args, **kwargs)
        # Personnalisation supplémentaire ici
        self.fields['email'].widget.attrs['readonly'] = True  # Rendre le champ 'username' en lecture seule
    
class UserAddressForm(forms.ModelForm):

    class Meta:
        model = UserAddress
        fields = [
            'street_address',
            'city',
        ]

    def __init__(self, *args, **kwargs):
        super().__init__(*args, **kwargs)

        for field in self.fields:
            self.fields[field].widget.attrs.update({
                'class': (
                    'block w-full mt-1 text-sm dark:border-gray-600 dark:bg-gray-700 focus:border-purple-400 focus:outline-none focus:shadow-outline-purple dark:text-gray-300 dark:focus:shadow-outline-gray form-input'
                )
            })


class UserRegistrationForm(UserCreationForm):

    class Meta:
        model = User
        fields = [
            'first_name',
            'last_name',
            'email',
            'password1',
            'password2',
        ]

    def __init__(self, *args, **kwargs):
        super().__init__(*args, **kwargs)

        for field in self.fields:
            self.fields[field].widget.attrs.update({
                'class': (
                    'appearance-none block w-full bg-gray-200 '
                    'text-gray-700 border border-gray-200 '
                    'rounded py-3 px-4 leading-tight '
                    'focus:outline-none focus:bg-white '
                    'focus:border-gray-500'
                )
            })

class UserBankAccountForm(forms.ModelForm):
    account_type = forms.ModelChoiceField(
        queryset=BankAccountType.objects.all()
    )
   
    class Meta:
        model = UserBankAccount
        labels = {
            'name': "Nom",
            'first_name': "Nom de famille", 
            'email': "Addresse email (pas obligatoire)",
            'phone': "Numèro de téléphone", 
            'gender': "Genre", 
            'birth_date': "Date de naissance (JOUR/MOI/ANNEE)", 
            'street_address':"Addresse physique",
            
            
        }
        fields = ['name', 
                  'first_name', 
                  'email',
                  'phone', 
                  'gender', 
                  'birth_date', 
                  'street_address', 
                  'account_type',
             
                ]
        
        
    def __init__(self, *args, **kwargs):
        super().__init__(*args, **kwargs)
            
        for field in self.fields:
            self.fields[field].widget.attrs.update({
                'class': (
                    'block w-full mt-1 text-sm dark:border-gray-600 dark:bg-gray-700 focus:border-purple-400 focus:outline-none focus:shadow-outline-purple dark:text-gray-300 dark:focus:shadow-outline-gray form-input'
                )
            })     

accounts/views.py
from django.contrib import messages
from django.shortcuts import render, redirect
from django.contrib.auth import get_user_model, login, logout
from django.contrib.auth.views import LoginView
from django.shortcuts import HttpResponseRedirect
from django.views.generic import CreateView
from django.contrib.auth.mixins import LoginRequiredMixin
from django.urls import reverse_lazy
from django.views.generic import TemplateView, RedirectView, View
from banking_system import settings
from accounts.models import UserBankAccount, UserAddress, BankAccountType
from transactions import utils
from .forms import UserRegistrationForm, UserAddressForm, UserBankAccountForm
from django.shortcuts import get_object_or_404
import datetime

User = get_user_model()

def register_user(request):
    form = UserRegistrationForm(request.POST or None)
    if form.is_valid():
        user = form.save()
        login(request, user)
        messages.success(
                request,
                (
                    f'Merci de pouvoir créer un compte agent ! '
                    f'Votre nom d\'utilisateur est  {user.first_name}! '
                )
            )
        
        return redirect('accounts:accounts_user')
        
    
    context = {
        'form': form
    }
    return render(request, 'accounts/user_registration.html', context)


def get_accounts(request):
    accounts = UserBankAccount.objects.filter(user=request.user)
    
    context = {
        'accounts': accounts    
    }
    return render(request, 'accounts/accounts_user.html', context)

    
def details_bank_account(request, pk):
    accounts = UserBankAccount.objects.filter(user=request.user)
    account = accounts.get(account_no=pk)
    
    context = {
        'account': account,
        'title': f'DETAILS {pk}'
    }
    return render(request, 'accounts/details.html', context)   

class UserRegistrationView(TemplateView):
    model = User
    form_class = UserRegistrationForm
    template_name = 'accounts/user_registration.html'

    def dispatch(self, request, *args, **kwargs):
        if self.request.user.is_authenticated:
            return HttpResponseRedirect(
                reverse_lazy('transactions:transaction_report')
            )
        return super().dispatch(request, *args, **kwargs)

    def post(self, request, *args, **kwargs):
        registration_form = UserRegistrationForm(self.request.POST)
        # address_form = UserAddressForm(self.request.POST)

        if registration_form.is_valid():
            #  and address_form.is_valid()
            user = registration_form.save()
            # address = address_form.save(commit=False)
            # address.user = user
            # address.save()
           

            login(self.request, user)
            messages.success(
                self.request,
                (
                    f'Thank You For Creating A Bank Account. '
                    f'Your Account Number is {user.account.account_no}. '
                )
            )
            return HttpResponseRedirect(
                reverse_lazy('transactions:deposit_money')
            )

        return self.render_to_response(
            self.get_context_data(
                registration_form=registration_form,
                # address_form=address_form
            )
        )

    def get_context_data(self, **kwargs):
        if 'registration_form' not in kwargs:
            kwargs['registration_form'] = UserRegistrationForm()
        # if 'address_form' not in kwargs:
        #     kwargs['address_form'] = UserAddressForm()

        return super().get_context_data(**kwargs)

def bank_account_create(request):
    
    form = UserBankAccountForm()
   
    
    if request.method == "POST":
        form = UserBankAccountForm(request.POST)
        if form.is_valid():
            
            account_type = str(form.cleaned_data.get('account_type'))
            
            typeid = BankAccountType.objects.get(name=account_type)
            account_num = str(settings.ACCOUNT_NUMBER_START_FROM) + str(settings.randomGen()) + "INSP"
                
            account_bank = form.save(commit=False)
            account_bank.user = request.user
            account_bank.account_type = typeid
            
            account_bank.save()
            
            messages.success(
                    request,
                    (
                        f'Thank You For Creating A Bank Account. '
                        f'Your Account Number is {account_bank}. '
                    )
                )
                
                
            return HttpResponseRedirect(
                    reverse_lazy('accounts:account_view')
                )
             
    context = {
      'form' : form,
    }
    return render(request, 'accounts/account_create.html', context)

def bank_account_edit(request, account_no):
    # Get the existing bank account based on the provided account ID
    bank_account = get_object_or_404(UserBankAccount, account_no=account_no, user=request.user)
    
    # Initialize the form with the existing bank account data
    form = UserBankAccountForm(instance=bank_account)
    
    if request.method == "POST":
        form = UserBankAccountForm(request.POST, instance=bank_account)
        if form.is_valid():
            # Save the updated bank account details
            form.save()
            
            messages.success(
                request,
                f'Your Bank Account has been successfully updated.'
            )
            
            return HttpResponseRedirect(
                reverse_lazy('accounts:account_view')
            )
    
    context = {
        'form': form,
    }
    return render(request, 'accounts/account_create.html', context)

class UserBankAccountView(LoginRequiredMixin, View):
    
    template_name = 'accounts/account_view.html'
    context = {
        "title" : "Comptes"
    }
    
    def post(self, request, *args, **kwargs):
        
        return render(request, self.template_name, self.context)
        
    def get(self, request, *args, **kwargs):
        accounts = UserBankAccount.objects.filter(user=request.user)
        items = utils.pagination(request, accounts)
        self.context['accounts'] = items
        
        
        return render(request, self.template_name, self.context)
            
class UserLoginView(LoginView):
    template_name='accounts/user_login.html'
    redirect_authenticated_user = False

class ProfileView(View):
    template_name = "accounts/profile.html"
    
    def get(self, request, *args, **kwargs):
        
        return render(request, self.template_name)
    
    
class LogoutView(RedirectView):
    pattern_name = 'index'

    def get_redirect_url(self, *args, **kwargs):
        if self.request.user.is_authenticated:
            logout(self.request)
        return super().get_redirect_url(*args, **kwargs)

accounts/templates/accounts/accounts_user.html
{% extends 'core/base.html' %} 
{% load humanize %} 
{% block head_title %}Transaction Report{% endblock %} 
{% block head_extra %}
<script type="text/javascript" src="https://cdn.jsdelivr.net/jquery/latest/jquery.min.js"></script>
<script type="text/javascript" src="https://cdn.jsdelivr.net/momentjs/latest/moment.min.js"></script>
<script type="text/javascript" src="https://cdn.jsdelivr.net/npm/daterangepicker/daterangepicker.min.js"></script>
<link rel="stylesheet" type="text/css" href="https://cdn.jsdelivr.net/npm/daterangepicker/daterangepicker.css" /> 
<link href="https://cdn.jsdelivr.net/npm/bootstrap@5.0.2/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-EVSTQN3/azprG1Anm3QDgpJLIm9Nao0Yz1ztcQTwFspd3yD65VohhpuuCOmLASjC" crossorigin="anonymous">
{% endblock %} 

{% block content %}
<div class="my-10 py-3 px-4 bg-white rounded-xl shadow-md">
    <h1 class="font-mono font-bold text-3xl text-center pb-5 pt-2">Comptes enregistrés recément</h1>
    
    <hr />
    <form method="get" id="filter">
        <div class="flex justify-center">
            <div class="mt-10 h-10 pl-3 pr-2 bg-white border rounded-md border-gray-500 flex justify-between items-center relative  w-4/12">
                <input type="search" name="daterange" id="search" placeholder="Filter using date range" class="appearance-none w-full outline-none focus:outline-none active:outline-none" autocomplete="off" value="{{ request.GET.daterange}}" />
                <button type="submit" class="ml-1 outline-none focus:outline-none active:outline-none">
                    <svg fill="none" stroke="currentColor" stroke-linecap="round" stroke-linejoin="round" stroke-width="2" viewBox="0 0 24 24" class="w-6 h-6">
                        <path d="M21 21l-6-6m2-5a7 7 0 11-14 0 7 7 0 0114 0z"></path>
                    </svg>
                </button>
            </div>
        </div>
        {% if form.daterange.errors %} {% for error in form.daterange.errors %}
        <p class="text-red-600 text-sm italic">{{ error }}</p>
        {% endfor %} {% endif %}
    </form>
    <table class="table-auto mx-auto w-full mt-8 border-collapse">
        <thead class="bg-gray-800 text-white">
            <tr class="uppercase font-semibold text-sm">
                <th class=" border border-black px-4 py-2">NUMERO</th>
                <th class=" border border-black px-4 py-2">NOM COMPLET</th>
                <th class=" border border-black px-4 py-2">E-MAIL</th>
                <th class=" border border-black px-4 py-2">TYPE DE COMPTE</th>

            </tr>
        </thead>
        <tbody>
            {% for account in accounts %}
            <tr class="{% cycle 'bg-gray-300' 'bg-white-100' %}">
                <td class="border border-blue-900 px-4 py-2"><a href="{% url 'accounts:details' account.account_no %}">{{ account.account_no }}</a></td>
                <td class="border border-blue-900 px-4 py-2">{{ account.first_name }} {{ account.last_name }}</td>
                <td class="border border-blue-900 px-4 py-2 text-right">{{ account.email }}</td>
                <td class="border border-blue-900 px-4 py-2 text-right">{{ account.account_type }}</td>
                
            </tr>
            {% endfor %}

        </tbody>
    </table>
</div>
{% endblock %} {% block footer_extra %}
<script type="text/javascript">
    var def_date = '{{request.GET.daterange}}'
    def_date = def_date == "" ? moment().format("Y-MM-DD") + " - " + moment().format("Y-MM-DD") : def_date
    var date_split = def_date.split(" - ")
    var start_date = moment(date_split[0]).format("MM/DD/Y")
    var end_date = moment(date_split[1]).format("MM/DD/Y")
    console.log(start_date, end_date)
    $(function() {
        $('input[name="daterange"]').daterangepicker({
            autoUpdateInput: false,
            startDate: start_date,
            endDate: end_date,
            locale: {
                cancelLabel: "Clear",
            },
        });

        $('input[name="daterange"]').on("apply.daterangepicker", function(ev, picker) {
            $(this).val(picker.startDate.format("YYYY-MM-DD") + " - " + picker.endDate.format("YYYY-MM-DD"));
            $('#filter').submit()
        });

        $('input[name="daterange"]').on("cancel.daterangepicker", function(ev, picker) {
            $(this).val("");
            $('#filter').submit()
        });
    });
</script>
{% endblock %}

accounts/templates/accounts/details.html
{% extends 'core/base.html' %} 
{% load crispy_forms_tags %}
{% load static %} {% block head_title %}{{title}}{% endblock %} {% block content %} {% if form.non_field_errors %} {% for error in form.non_field_errors %}
<div class="bg-red-100 border border-red-400 text-red-700 px-4 py-3 rounded relative mt-2" role="alert">
    <p class="font-bold">Error!</p>
    <p class="block sm:inline">{{ error }}</p>
</div>
<!-- {% endfor %} {% endif %} {% if address_form.non_field_errors %} {% for error in address_form.non_field_errors %}
<div class="bg-red-100 border border-red-400 text-red-700 px-4 py-3 rounded relative mt-2" role="alert">
    <p class="font-bold">Error!</p>
    <p class="block sm:inline">{{ error }}</p>
</div>
{% endfor %} {% endif %} -->
<div class="bg-white px-3 py-4 rounded-xl">
    <h1 class="font-mono font-bold text-3xl text-center pb-5">{{title}}</h1>
    <hr />
    <div class="w-full flex mt-5 justify-center">

   
    <div class="bg-white w-8/12">
      
    </div>
</div>
</div>
{% endblock %}

accounts/templates/accounts/subaccount.html
{% extends 'core/base.html' %} {% block head_title %}{{ title }}{% endblock %} {% block content %}

<div class="w-full flex mt-5 justify-center">
    <div class="bg-white w-8/12">
        <h1 class="font-mono font-bold text-3xl text-center pb-5 pt-10 px-5">{{ title }}</h1>
        <hr />

        {% if subaccount %}

        <div id="accordion-open" data-accordion="open">

            {% for sub in subaccount%}

            <h2 id="accordion-open-heading-1">
                <button type="button"
                    class="flex items-center justify-between w-full p-5 font-medium text-left text-gray-500 border border-b-0 border-gray-200 rounded-t-xl focus:ring-4 focus:ring-gray-200 dark:focus:ring-gray-800 dark:border-gray-700 dark:text-gray-400 hover:bg-gray-100 dark:hover:bg-gray-800"
                    data-accordion-target="#accordion-open-body-1" aria-expanded="true"
                    aria-controls="accordion-open-body-1">
                    <span class="flex items-center"><svg class="w-5 h-5 mr-2 shrink-0" fill="currentColor"
                            viewBox="0 0 20 20" xmlns="http://www.w3.org/2000/svg">
                            <path fill-rule="evenodd"
                                d="M18 10a8 8 0 11-16 0 8 8 0 0116 0zm-8-3a1 1 0 00-.867.5 1 1 0 11-1.731-1A3 3 0 0113 8a3.001 3.001 0 01-2 2.83V11a1 1 0 11-2 0v-1a1 1 0 011-1 1 1 0 100-2zm0 8a1 1 0 100-2 1 1 0 000 2z"
                                clip-rule="evenodd"></path>
                        </svg> {{sub.motif}}</span>
                    <svg data-accordion-icon class="w-6 h-6 rotate-180 shrink-0" fill="currentColor" viewBox="0 0 20 20"
                        xmlns="http://www.w3.org/2000/svg">
                        <path fill-rule="evenodd"
                            d="M5.293 7.293a1 1 0 011.414 0L10 10.586l3.293-3.293a1 1 0 111.414 1.414l-4 4a1 1 0 01-1.414 0l-4-4a1 1 0 010-1.414z"
                            clip-rule="evenodd"></path>
                    </svg>
                </button>
            </h2>
            <div id="accordion-open-body-1" class="hidden" aria-labelledby="accordion-open-heading-1">
                <div class="p-5 font-light border border-b-0 border-gray-200 dark:border-gray-700 dark:bg-gray-900">

                    <div class="relative overflow-x-auto shadow-md sm:rounded-lg">
                        <table class="w-full text-sm text-left text-gray-500 dark:text-gray-400">
                            <thead class="text-xs text-gray-700 uppercase dark:text-gray-400">
                                <tr>
                                    <th scope="col" class="px-6 py-3 bg-gray-50 dark:bg-gray-800">
                                        SOUS NUMERO ID
                                    </th>

                                    <th scope="col" class="px-6 py-3 bg-gray-50 dark:bg-gray-800">
                                        ACTIVE
                                        
                                    </th>
                                    <th scope="col" class="px-6 py-3">
                                        BALANCE
                                    </th>

                                    <th scope="col" class="px-6 py-3">
                                        DATE
                                    </th>
                                </tr>
                            </thead>
                            <tbody>
                                <tr class="border-b border-gray-200 dark:border-gray-700">
                                    <th scope="row"
                                        class="px-6 py-4 font-medium text-gray-900 whitespace-nowrap bg-gray-50 dark:text-white dark:bg-gray-800">
                                        {{sub.subaccount_no}}
                                    </th>
                                    <td class="px-6 py-4">

                                        {% if sub.is_active == True %}
                                        
                                        <p class="text-4xl text-gray-900 dark:text-green">ACTIVE</p>
                                        {% else %}
                                        NON ACTIVE
                                        {% endif %}

                                    </td>
                                    <td class="px-6 py-4 bg-gray-50 dark:bg-gray-800">
                                        {{sub.balance}}
                                    </td>
                                    <td class="px-6 py-4">

                                        {{sub.added_at}}
                                    </td>
                                </tr>
                            </tbody>
                        </table>
                    </div>

                </div>
            </div>

            {% endfor %}
        </div>
        {% else %}
        <p class="font-light text-gray-500 warning:text-gray-400">Vous n'avez créer de sous comptes</p>
        {% endif %}
    </div>
</div>


{% endblock %}

accounts/templates/accounts/subaccount_create.html
{% extends 'core/base.html' %} {% block head_title %}{{ title }}{% endblock %} {% block content %}

<div class="w-full flex mt-5 justify-center">
    <div class="bg-white w-5/12">
        <h1 class="font-mono font-bold text-3xl text-center pb-5 pt-10 px-5">{{ title }}</h1>
        <hr />
        <form method="post" class="px-8 pt-6 pb-8 mb-4">
            {% csrf_token %}

            <div class="w-full px-3 mb-6 md:mb-0">
                <label class="block uppercase tracking-wide text-gray-700 text-xs font-bold mb-2" for="{{ address_form.postal_code.id_for_label }}">
                    {{ form.motif.label }}
                </label> {{ form.motif }} {% if form.motif.errors %} {% for error in form.motif.errors %}
                <p class="text-red-600 text-sm italic pb-2">{{ error }}</p>
                {% endfor %} {% endif %}
            </div>
            <div class="w-full px-3">
                <label class="block uppercase tracking-wide text-gray-700 text-xs font-bold mb-2" for="{{ address_form.country.id_for_label }}">
                    {{ form.balance.label }}
                </label> {{ form.balance }} {% if form.balance.errors %} {% for error in form.balance.errors %}
                <p class="text-red-600 text-sm italic pb-2">{{ error }}</p>
                {% endfor %} {% endif %}
            </div>
            <br>
            <br>
            <div class="flex items-center justify-between">
                <button class="bg-blue-500 hover:bg-blue-700 text-white font-bold py-2 px-4 rounded focus:outline-none focus:shadow-outline" type="submit">
                    Créer un sous compte
                </button>
            </div>
        </form>
    </div>
</div>
{% endblock %}